// ─── Hero Slides ───
const heroSlides = [
  { title: "Premium Pathways to Ausbildung & Global Careers in Germany", description: "Earn While You Learn. Secure a Recognized German Qualification. Build a Long-Term Career in Europe.", ctaText: "Apply Now", ctaLink: "contact.html" },
  { title: "Job For Nurses in Germany", description: "Germany healthcare jobs for nurses providing competitive pay, permanent opportunities, and professional growth in modern medical systems.", ctaText: "Learn More", ctaLink: "healthcare.html" },
  { title: "Study Abroad & Build a Global Future", description: "Get expert guidance for admissions, visas, and career-focused international education opportunities.", ctaText: "Explore", ctaLink: "study-abroad.html?country=germany" },
];

// ─── Trust Indicators ───
const trustIndicators = [
  { value: "99.7%", label: "Visa Approval Rate" },
  { value: "1,000+", label: "Successful Journeys" },
  { value: "30+", label: "Global Destinations" },
  { value: "10+", label: "Specialized Immigration & Career Services" },
];

// ─── Ausbildung Programs ───
const ausbildungPrograms = [
  { title: "Radiology Assistant", slug: "radiology-assistant", description: "Radiology assistant jobs in Germany offering advanced medical facilities, stable careers, and competitive salaries.", overview: "A three-year Ausbildung program training candidates in diagnostic imaging, radiological procedures, and patient care within Germany's world-class healthcare system. Graduates work in hospitals, clinics, and diagnostic centres operating cutting-edge medical equipment.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Team player, attention to detail" }] },
  { title: "Medical Assistant", slug: "medical-assistant", description: "Job-ready Medical Assistant programs focused on international standards, skills development, and overseas career pathways.", overview: "A three-year Ausbildung program combining classroom instruction with hands-on clinical training. Medical assistants support doctors with patient examinations, lab work, administrative duties, and medical documentation in German healthcare facilities.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Team player, organized" }] },
  { title: "Nursing", slug: "nursing", description: "Three-year apprenticeship designed for individuals pursuing a career in nursing, providing internationally recognized vocational training in Germany.", overview: "A three-year apprenticeship designed for aspiring nurses, offering internationally recognized vocational training in Germany. The dual program combines formal instruction with practical experience, equipping candidates with the necessary skills and certifications to work in hospitals, care homes, and community health centers across Germany.", benefits: ["Stipend (Year 1–3): €980 – €1,250 / Month", "Salary after apprenticeship: €3,000 / Month", "Recognized RN qualification", "Subsidised accommodation", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000 / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Team player" }] },
  { title: "Electrical Engineer", slug: "electrical-engineer", description: "Engineering programs designed for global careers with practical training, technical skills, and international industry standards.", overview: "A three-year Ausbildung program in electrical engineering covering installation, maintenance, and repair of electrical systems in industrial and commercial settings.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Technical aptitude, problem solver" }] },
  { title: "Mechanic", slug: "mechanic", description: "Mechanic programs in Germany for hands-on vocational training, tool mastery, and long-term employment in automotive and industrial sectors.", overview: "A three-year Ausbildung program training candidates in mechanical maintenance, diagnostics, and repair of machinery and vehicles.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Hands-on, detail-oriented" }] },
  { title: "Automotive Mechatronic Technician", slug: "automotive-mechatronic", description: "Paid Ausbildung in Germany for automotive mechatronic technicians with hands-on training and strong career prospects.", overview: "A three-year Ausbildung program focused on diagnosing, repairing, and maintaining modern vehicles including electric and hybrid systems.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Technical aptitude, problem solver" }] },
  { title: "Mechatronics & Electronics", slug: "mechatronics-electronics", description: "Advanced mechatronics and electronics training combining mechanical engineering, electrical systems, and IT for industry-ready careers in Germany.", overview: "A three-year Ausbildung program at the intersection of mechanical engineering, electronics, and information technology.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Analytical, tech-savvy" }] },
  { title: "Bakers", slug: "bakers", description: "Professional bakery training in Germany with hands-on experience in artisan bread-making, pastry, and German baking traditions.", overview: "A three-year Ausbildung program in the baking profession, combining traditional German baking techniques with modern production methods.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Creative, physically fit" }] },
  { title: "Food Processing", slug: "food-processing", description: "Professional food processing training designed for overseas opportunities with practical skills and global standards.", overview: "A three-year Ausbildung program in food technology and processing, covering quality control, production processes, hygiene regulations, and packaging.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Detail-oriented, hygienic" }] },
  { title: "Logistics", slug: "logistics", description: "Professional logistics programs designed for overseas opportunities with hands-on supply chain management training.", overview: "A three-year Ausbildung program in logistics and warehousing, covering supply chain management, inventory control, shipping operations, and modern logistics technology.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–27 years" }, { label: "Education", value: "12th / ITI / Diploma" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Organized, physically fit" }] },
  { title: "Truck Drivers", slug: "truck-drivers", description: "Heavy truck driver jobs in Germany offering stable employment, competitive salaries, long-term careers, and full support for relocation.", overview: "A structured training and placement program for professional truck drivers seeking employment in Germany.", benefits: ["Monthly stipend starting approximately ₹90,000", "Secure long-term employment after completion", "Industry-focused certifications recognized globally", "Permanent residency eligibility after 5 years", "No blocked account required", "No IELTS required", "Overtime earning opportunities", "Legally secure employment pathway"], stipend: "€980 – €1,250 / Month (Year 1–3)", postTrainingSalary: "€3,000+ / Month", accommodation: "Subsidised accommodation", eligibility: [{ label: "Age", value: "18–35 years" }, { label: "Education", value: "10th / 12th" }, { label: "Language", value: "B1 German" }, { label: "Skills", value: "Disciplined, experienced driver" }] },
];

// ─── Why Germany ───
const whyGermany = [
  { title: "Strong Demand for Skilled Professionals", description: "Germany faces a critical shortage of skilled workers across healthcare, engineering, logistics, and trades, creating thousands of open positions for qualified international candidates." },
  { title: "Attractive Salaries and Benefits", description: "German employers offer competitive pay, health insurance, paid holidays, overtime compensation, and retirement benefits as standard for all employees." },
  { title: "Access to the European Market", description: "Working in Germany provides access to the entire EU job market, enabling career mobility across 27 European nations." },
  { title: "Fast, Legal, and Transparent Entry", description: "Germany's Ausbildung visa pathway is legally structured, transparent, and designed to bring skilled international candidates into the country efficiently." },
  { title: "Stable & Secure Employment", description: "Germany's strong economy and labour protections ensure long-term job security, with most Ausbildung graduates receiving permanent employment offers." },
  { title: "World-Class Education and Healthcare", description: "Residents benefit from Germany's free or low-cost education system and universal healthcare coverage for themselves and their families." },
];

// ─── About Ausbildung ───
const aboutAusbildung = {
  description: "Ausbildung is a structured three-year vocational training program in Germany that allows candidates to earn while they learn, gain real-world work experience, and build a secure pathway toward long-term employment and permanent residency.",
  keyFeatures: [
    { title: "Dual Education Model", detail: "Combines practical work experience with classroom learning." },
    { title: "Duration", detail: "Typically runs for three years, varying by profession and performance." },
    { title: "Certification", detail: "Grants a nationally recognized German qualification upon completion." },
    { title: "Employment Opportunities", detail: "Most graduates secure full-time jobs after training." },
    { title: "Proven Track Record", detail: "1,000+ candidates trained, with 600+ currently in Germany." },
  ],
};

const ausbildungBenefits = [
  "Monthly stipend starting approximately ₹90,000",
  "Secure long-term employment after completion",
  "Industry-focused certifications recognized globally",
  "Permanent residency eligibility after 5 years",
  "No blocked account required",
  "No IELTS required",
  "Overtime earning opportunities",
  "Legally secure employment pathway",
];

const otherCourses = [
  { category: "Healthcare", courses: ["Dental Assistant", "Physiotherapy"] },
  { category: "Hospitality", courses: ["Hospitality & Tourism", "Event Management", "Chef", "Hotel Specialist"] },
  { category: "Commerce", courses: ["Administration", "Sales & Retail", "Bank Clerk"] },
  { category: "Technical", courses: ["Aircraft Construction / Mechatronic", "IT & Computer Science"] },
];

const programInclusions = [
  "Document Verification & Validation", "Personalized Candidate Profiling", "Interview Preparation & Skill Training",
  "German Language Training", "German Culture & Program Orientation", "Continuous Employer Coordination",
  "Employer Interview Scheduling", "Guaranteed Job Offer Support", "Visa Documentation Assistance",
  "Pre & Post-Arrival Support", "3-Month Post-Deployment Assistance", "Vocational Certification",
];

const germanLanguageFeatures = [
  "Self-Practice Materials", "Complete Study Resources", "Expert-Level Instructors",
  "Comprehensive Live Training", "Small Batch Learning", "Practical Communication Sessions",
];

const candidateJourney = [
  { title: "Enroll", description: "Register and begin your journey with Bright Institutes." },
  { title: "Documentation", description: "We assist with all required document preparation." },
  { title: "Screening Round", description: "Initial candidate screening and assessment." },
  { title: "Conditional Offer Letter", description: "Receive your conditional job offer from Germany." },
  { title: "Pre-training Commencement", description: "Begin your pre-departure orientation and preparation." },
  { title: "B1 German Language Completion", description: "Complete German language training up to B1 level." },
  { title: "Interaction with German Employers", description: "Interview and finalize placement with your employer." },
  { title: "Visa Process", description: "Submit documents and apply for your visa." },
  { title: "Visa Approval", description: "Receive your approved visa." },
  { title: "Fly to Germany", description: "Relocate and start your career in Germany." },
];

// ─── Services ───
const services = [
  { title: "Study Abroad Support", description: "Complete assistance with overseas education, including university selection, application processing, admissions, and pre-departure guidance." },
  { title: "Blue-Collar Migration Solutions", description: "End-to-end assistance for trade and essential workers, from employer sponsorship and job matching to work permits and overseas placement." },
  { title: "Immigration Services", description: "Expert support for all skilled, semi-skilled, and unskilled professionals covering permanent residency options, documentation, and structured immigration pathways for global career growth." },
  { title: "Live Learning & Language Training", description: "Instructor-led training for IELTS, PTE, OET, and CELPIP, along with foreign language programs in German, French, Japanese, and more." },
  { title: "International Job Search Assistance", description: "Connecting professionals with global employment opportunities, supported by visa processing, job coordination, and post-arrival assistance." },
  { title: "Post-Landing & Settlement Services", description: "Comprehensive support for new immigrants, including accommodation assistance, health insurance, bank account setup, and local orientation." },
  { title: "Hajj & Umrah Services", description: "Trusted partner for a blessed journey to the Holy Land with carefully curated deluxe and budget packages." },
  { title: "Visit Visa", description: "Expert assistance for tourist and visit visas. Whether visiting family, attending conferences, or traveling for leisure." },
  { title: "Opportunity Card", description: "Your gateway to the German job market. Live in Germany exploring job opportunities with a pathway to the EU Blue Card, with no upfront job offer required." },
];

const visaTypes = ["Visit Visa", "VISA PROCESSING", "VISA Consulting", "Air Ticketing", "Students visa", "Family Visa", "Business Visa", "Travel Visa", "Working Visa", "Visa Management"];

const contactInfo = {
  phones: ["+91-9963222881", "+91-7816001097"],
  email: "info@brightinstitutes.in",
  offices: [
    { title: "Branch Office", address: "3rd Floor A Block, Synosoft Building, Lakdi ka pool Hyderabad. Pin code: 500 004. T.S. India." },
    { title: "Head Office", address: "Edi bazar Santosh nagar Hyderabad..500 023" }
  ],
  aboutText: "Bright Institutes & Overseas is a reputable organization specializing in overseas education and recruitment services, supporting individuals and families in achieving their ambitions to study, work, and settle abroad.",
  aboutFull: "Backed by years of experience and an expanding global reach, we have positioned ourselves as a dependable partner for immigration assistance, skill training, and international career pathways.",
  mission: "Our services include visa guidance, language training in German, French, English, Arabic, and other global languages, along with job placement support and comprehensive post-arrival assistance.",
  whyUs: "By offering personalized guidance, expert support, and ethical service standards, Bright Institutes & Overseas helps candidates confidently transform their international career goals into reality.",
  training: "Our practical training approach, experienced faculty, and student-focused methodology ensure consistent results and career readiness.",
  closing: "With transparency, commitment, and quality at our core, Bright Institutes continues to empower learners to achieve their global education and career goals with confidence.",
};

// ─── Testimonials ───
const testimonials = [
  { name: "Vamsi Shah", text: "Bright Institutes provided excellent German language training and complete overseas guidance, helping me confidently plan my education and career opportunities in Germany." },
  { name: "Gunasatya Reddy", text: "I had a great experience with Bright Institute while planning my MBBS journey. From university selection to documentation, visa process, and even post-admission support, they were always available and guided me with complete transparency." },
  { name: "Kasim Ali", text: "I recently used Bright Institute consultancy services for my study abroad journey to Canada, for a Master's program, and I'm thoroughly impressed with their services. From the initial consultation to receiving my visa, the team was professional, knowledgeable, and incredibly supportive." },
  { name: "Shahid Ansar", text: "I am truly grateful to Bright team for her constant guidance and support throughout my journey. She has helped me at every step, right from choosing the right university to encouraging me whenever I faced doubts. What makes her guidance even more special is that she was always available to help." },
];

// ─── Nurse Page Content ───
const nursePageContent = {
  heroTitle: "Job For Nurses in Germany",
  heroDescription: "Germany healthcare jobs for nurses providing competitive pay, permanent opportunities, and professional growth in modern medical systems.",
  salaryTitle: "Nurses In Germany Earn ₹3.5-4 Lakhs Per Month",
  salaryDescription: [
    "Germany offers nurses high job security, excellent pay & professional growth opportunities. Work in a world-class healthcare system with access to advanced training & resources",
    "This is a 3-year apprenticeship designed for aspiring nurses, offering internationally recognized vocational training in Germany. The dual program combines formal instruction with practical experience, equipping candidates with the necessary skills and certifications to work in hospitals, care homes, and community health centers across Germany.",
    "A complete end-to-end program that helps Indian nurses learn German, secure a job in Germany, relocate with family, and build a high-income global career",
    "Germany is currently facing a critical shortage in the nursing sector, with estimates indicating a need for more than 500,000 skilled workers by 2030 to meet its growing healthcare demands.",
  ],
  benefits: "Stipend (Year 1–3): €980- €1250/ Month Salary after apprenticeship: €3000 / Month Recognized RN qualification Subsidised Accommodation Fees: ₹3L + GST",
  eligibilityCriteria: [
    { title: "German Language Training", description: "A1 to B2 level training with training fees and B1/B2 exam fees fully reimbursed." },
    { title: "Free Interview Training", description: "Expert preparation to help you succeed in your interviews." },
    { title: "Free Documentation Support", description: "Get complete assistance with the official documentation process in your home country, including examination, translation, and certification." },
    { title: "Free Visa and Permit Assistance", description: "Support with applying for your visa, residence permit, and work permit." },
    { title: "Free Relocation Support", description: "Coordination of your flight and transfer from the airport to your accommodation." },
    { title: "Free Administrative Guidance", description: "Assistance with setting up a bank account, obtaining health insurance, securing a social security number, and acquiring a SIM card." },
    { title: "Family Reunification Support", description: "Help with family reunification processes, including language courses for your spouse." },
  ],
  journeySteps: [
    { title: "Start with ₹10,000 + GST", description: "Start with A1 level of German Language (Foundation)" },
    { title: "Pay ₹90,000 + GST, after clearing A1", description: "German for everyday and nursing communication" },
    { title: "Clear B1", description: "After clearing B1 – Your interview & visa process starts" },
    { title: "Departure", description: "After clearing B2 – Fly to Germany & start working" },
  ],
  faqs: [
    { question: "Who can apply for nursing jobs in Germany?", answer: "Qualified nurses with recognized nursing education and required German language proficiency can apply." },
    { question: "Is German language mandatory for nurses in Germany?", answer: "Yes, German language proficiency (usually B1/B2 level) is mandatory to work as a nurse in Germany." },
    { question: "Do nurses need registration to work in Germany?", answer: "Yes, nurses must complete the German recognition and registration process before working." },
    { question: "What is the salary range for nurses in Germany?", answer: "Salaries vary by region and experience, generally offering stable income with additional benefits." },
    { question: "Is visa assistance provided?", answer: "Yes, we offer complete visa guidance and documentation support until visa approval." },
  ],
};

// ─── Study Abroad Countries ───
const studyCountries = [
  { name: "Study In Germany", slug: "germany", shortDescription: "Germany is known for its world-class universities, affordable education, and strong career opportunities.", fullDescription: ["Germany is one of the most sought-after destinations for international students, offering world-class education, globally recognized degrees, and excellent career opportunities.", "One of the key advantages of studying in Germany is the affordability of education. Many public universities offer tuition-friendly or low-cost programs.", "Germany is also renowned for its practical learning approach. Universities emphasize research, industry exposure, and skill development.", "For students planning their academic journey, German language proficiency plays a vital role. We provide comprehensive guidance.", "Beyond academics, Germany offers a safe, culturally diverse, and student-friendly environment."], visaProcessTitle: "Germany Visa Process", visaSteps: [{ title: "Admission / Offer Letter", description: "The visa process begins after receiving an official admission letter from a German university." }, { title: "Document Preparation", description: "Gather and organize required documents including passport, admission letter, financial proof, and more." }, { title: "Visa Appointment", description: "Schedule an appointment with the German Embassy / Consulate / VFS Center." }, { title: "Visa Interview", description: "Attend the visa interview. Our team provides interview preparation." }, { title: "Visa Processing", description: "The embassy evaluates the application." }, { title: "Visa Approval & Stamping", description: "Upon approval, the visa is stamped on your passport." }] },
  { name: "Study In Russia", slug: "russia", shortDescription: "Russia is a globally recognized destination offering high-quality education in medical, engineering, and diverse academic programs with affordable tuition fees.", fullDescription: ["Studying in Russia offers international students an excellent opportunity to gain high-quality education at affordable costs, especially in fields like medicine, engineering, and aviation.", "Russian universities are recognized by major global organizations like WHO and UNESCO, ensuring the degrees hold international value.", "The country provides a vibrant multicultural environment with modern campus facilities and student-friendly living conditions.", "At Bright Institutes, we provide end-to-end guidance from university selection to visa processing for your Russian study journey."], visaProcessTitle: "Russia Visa Process", visaSteps: [{ title: "Select University & Program", description: "Choose a recognized Russian university and program." }, { title: "Receive Invitation Letter", description: "Obtain an official invitation letter issued by the Ministry of Interior of the Russian Federation." }, { title: "Prepare Documents", description: "Gather your passport, educational certificates, HIV test certificate, and photographs." }, { title: "Apply for Visa", description: "Submit your student visa application to the Russian Embassy or Consulate." }, { title: "Attend Visa Interview", description: "If required, attend a brief interview at the consulate." }, { title: "Visa Stamping", description: "Once approved, your Russian student visa will be stamped on your passport." }, { title: "Travel to Russia", description: "Arrive in Russia and complete university registration and medical insurance processes." }] },
  { name: "Study In New Zealand", slug: "new-zealand", shortDescription: "New Zealand offers a world-class education system, stunning natural landscapes, and a safe, welcoming environment for international students.", fullDescription: ["Studying in New Zealand provides an exceptional blend of high-quality education and an incredible lifestyle. Its universities are globally recognized for excellence in research and innovation.", "Students benefit from a practical, hands-on learning approach embedded in the curriculum. The education system encourages independent thinking and problem-solving.", "New Zealand is consistently ranked as one of the safest and most peaceful countries in the world, making it an ideal destination for international students.", "At Bright Institutes, we provide comprehensive guidance for students aspiring to study in New Zealand."], visaProcessTitle: "New Zealand Visa Process", visaSteps: [{ title: "Apply to an Institution", description: "Secure an offer of place from an approved New Zealand education provider." }, { title: "Pay Tuition Fees", description: "Pay your first year's tuition or show you have sufficient funds." }, { title: "Prepare Documents", description: "Gather passport, offer letter, proof of funds, medical and police certificates." }, { title: "Submit Online Application", description: "Apply for the student visa through the Immigration New Zealand online portal." }, { title: "Medical & Character Checks", description: "Complete necessary health and character verifications." }, { title: "Visa Decision", description: "Once approved, you will receive an eVisa with your conditions." }] },
  { name: "Study In Australia", slug: "australia", shortDescription: "Studying abroad in Australia offers students an incredible opportunity to experience world-class education, a safe and.", fullDescription: ["Studying abroad in Australia offers students an incredible opportunity to experience world-class education, a safe and welcoming environment, and strong career pathways. Known for its high academic standards, modern universities, and practical learning approach, Australia has become one of the most preferred destinations for international students.", "One of the biggest advantages of studying in Australia is the country's excellent focus on hands-on learning and industry exposure. Students can work part-time while studying and gain real-world experience.", "Australia is also known for its multicultural environment, high quality of life, and student-friendly cities such as Sydney, Melbourne, Brisbane, Perth, and Adelaide.", "From preparing your documents to choosing the right university, Bright Associates Education & Immigration provides complete guidance through every step of your journey."], visaProcessTitle: "Australia Visa Process", visaSteps: [{ title: "Consultation & Eligibility Check", description: "Our experts review your profile and visa requirements." }, { title: "Choose Your Course & Institution", description: "Students must select a course and university/college registered under CRICOS." }, { title: "Receive the Offer Letter", description: "After submitting academic and language documents, the institution issues a Conditional or Unconditional Offer Letter." }, { title: "Confirm Enrollment (CoE)", description: "Once the student accepts the offer and pays the initial tuition fee, the institution issues a Confirmation of Enrolment." }, { title: "Prepare GTE Statement", description: "The GTE explains your purpose of studying in Australia. A strong GTE increases visa approval chances." }, { title: "Arrange Financial Proof", description: "You must show funds to cover tuition fees, living expenses, and travel costs." }, { title: "Get OSHC", description: "OSHC is compulsory medical insurance for the entire duration of your stay." }, { title: "Submit Online Visa Application", description: "Apply via ImmiAccount with all required documents." }, { title: "Biometrics & Medical Examination", description: "You must attend a medical exam and give biometrics at an approved center." }, { title: "Visa Decision", description: "If approved, you receive a Visa Grant Letter with visa conditions." }, { title: "Pre-Departure & Travel", description: "Once the visa is granted: Book flights, arrange accommodation, and travel to Australia." }] },
  { name: "Study In USA", slug: "usa", shortDescription: "We align your academic background, career goals, and budget with the best US study options.", fullDescription: ["The United States is one of the most sought-after destinations for international students, offering unmatched academic excellence, research opportunities, and career pathways.", "Whether you're interested in engineering, computer science, business, healthcare, arts, finance, biotechnology, or any specialized field, American institutions offer thousands of programs.", "Studying in the USA also gives students the flexibility to personalize their learning through electives, minors, and interdisciplinary programs.", "With opportunities such as CPT and OPT, students can gain real-world work experience in leading industries.", "At Bright Associates Education & Immigration, we guide students through every step of their USA study journey."], visaProcessTitle: "USA Visa Process", visaSteps: [{ title: "Get Admission & Receive Form I-20", description: "Once accepted by a SEVP-approved university, you will receive the I-20 Form." }, { title: "Pay the SEVIS Fee", description: "Before applying for the F-1 visa, you must pay the SEVIS I-901 fee online." }, { title: "Complete the DS-160 Visa Application", description: "Fill out the DS-160 form online." }, { title: "Pay the Visa Fee & Book Appointments", description: "Pay the MRV visa fee and schedule biometrics and visa interview appointments." }, { title: "Attend the Biometrics Appointment", description: "Your fingerprints and photograph will be taken." }, { title: "Attend the F-1 Visa Interview", description: "The visa officer will ask about your university, financial capability, and future goals." }, { title: "Receive Your F-1 Visa", description: "Once issued, you will get your passport with an F-1 visa stamp." }, { title: "Travel to the USA", description: "U.S. Customs will review your documents and issue an I-94 entry record." }, { title: "Begin Your Studies", description: "Join your institution and start your academic journey in the USA." }] },
  { name: "Study In UK", slug: "uk", shortDescription: "We provide expert guidance and end-to-end support for students planning to study in the United Kingdom.", fullDescription: ["The United Kingdom offers world-class education, rich cultural experiences, and globally recognized degrees.", "One of the biggest advantages is affordable tuition fees, low living costs, and scholarships for international students.", "With access to 25+ Schengen countries, students enjoy the freedom to travel and explore new cultures.", "At Bright Associates Education & Immigration, we help students choose the right country based on their goals, budget, and career plans."], visaProcessTitle: "UK Visa Process", visaSteps: [{ title: "Receive Your CAS", description: "After securing admission, the university will issue a CAS Letter." }, { title: "Prepare Required Documents", description: "Collect passport, CAS letter, academic transcripts, English proficiency test, proof of financial support." }, { title: "Apply Online for the UK Student Visa", description: "Complete your visa application on the UK Home Office website." }, { title: "Book Your Biometrics Appointment", description: "Schedule an appointment at a VFS Global center." }, { title: "Attend the Interview (If Required)", description: "Answer questions about your course, university, and financial stability." }, { title: "Visa Processing & Approval", description: "UK visa processing usually takes 3–6 weeks." }, { title: "Travel & Arrive in the UK", description: "Collect your BRP Card from the designated Post Office within 10 days." }, { title: "Start Your Studies & Work Rights", description: "Students can work 20 hours per week during term, full-time during holidays." }] },
  { name: "Study In Europe", slug: "europe", shortDescription: "Europe offers world-class education, rich cultural experiences, and globally recognized degrees.", fullDescription: ["Europe is one of the most prestigious and diverse study destinations in the world.", "One of the biggest advantages is affordable tuition fees, low living costs, and scholarships.", "With access to 25+ Schengen countries, students enjoy the freedom to travel and broaden their global perspective.", "At Bright Associates Education & Immigration, we help students choose the right European country."], visaProcessTitle: "Europe Visa Process", visaSteps: [{ title: "Choose Your Country, Course & University", description: "Select the European country and course based on your academic goals." }, { title: "Prepare Required Documents", description: "Gather passport, admission letter, proof of funds, academic transcripts, and more." }, { title: "Pay Tuition Fee & Secure Accommodation", description: "Most universities require partial tuition fee payment in advance." }, { title: "Book Visa Appointment", description: "Schedule an appointment at the nearest Embassy / Consulate / VFS Global center." }, { title: "Attend Visa Interview", description: "Be prepared to discuss your chosen course, future career plans, and financial support." }, { title: "Visa Approval & Travel", description: "Once approved, you will receive your Study Visa." }, { title: "Residence Permit After Arrival", description: "In many countries, you must apply for a Residence Permit within 30–90 days." }] },
  { name: "Study In Canada", slug: "canada", shortDescription: "Canada is one of the world's most preferred study destinations, known for exceptional education standards.", fullDescription: ["Canada is one of the world's most preferred study destinations, known for its exceptional education standards, safe environment, and strong career prospects.", "Canadian universities and colleges are ranked among the best globally, offering modern campuses and advanced learning facilities.", "One of the biggest advantages is its welcoming and inclusive environment with high safety standards and excellent healthcare.", "At Bright Associates Education & Immigration, we guide you through every step of your Canada study journey.", "Begin your journey to a bright future with Canada's world-class education."], visaProcessTitle: "Canada Visa Process", visaSteps: [{ title: "Select Your Course & DLI", description: "Choose a program and institution recognized as a Designated Learning Institution." }, { title: "Receive the Letter of Acceptance", description: "The institution will issue a Letter of Acceptance confirming your admission." }, { title: "Gather Required Documents", description: "Valid passport, LOA, proof of funds, English test score, SOP, PCC." }, { title: "Proof of Funds", description: "Show sufficient funds for first-year tuition, living expenses, and travel." }, { title: "Pay Tuition Fee & Buy GIC", description: "For SDS: Pay one-year tuition fee and purchase a CAD 20,635 GIC." }, { title: "Submit Your Online Visa Application", description: "Create an account on IRCC and upload all documents." }, { title: "Give Biometrics", description: "Visit your nearest VAC center to submit fingerprints and photo." }, { title: "Medical Examination", description: "Undergo a medical exam with an IRCC-approved panel physician." }, { title: "Visa Decision", description: "If approved, you receive a Port of Entry Letter and Visa Stamp." }, { title: "Travel to Canada", description: "Carry all documents. At the airport, the officer will issue your Study Permit." }] }
];

// ─── Language Courses ───
const languageCourses = [
  { title: "German Language Training", slug: "german", fullDescription: ["German language proficiency is a key requirement for anyone planning to study, work, or build a long-term career in Germany. Our German Language Training program follows the CEFR, covering levels from A1 to C2.", "Our training methodology focuses on interactive and practical learning with role plays, group discussions, and real-life scenarios.", "The program is guided by experienced and certified trainers who understand the specific language requirements for German universities and Ausbildung programs.", "Students receive guidance on German culture, workplace communication, and formal language usage.", "Our German Language Training is ideal for students planning to pursue higher education, vocational training, or employment opportunities in Germany."], levels: [{ level: "A1 – Beginner", description: "Understand and use basic everyday expressions and simple sentences." }, { level: "A2 – Elementary", description: "Communicate in routine situations and understand frequently used phrases." }, { level: "B1 – Intermediate", description: "Handle daily conversations, work situations, and express opinions clearly." }, { level: "B2 – Upper Intermediate", description: "Communicate fluently and understand complex texts and professional discussions." }, { level: "C1 – Advanced", description: "Use German effectively for academic and professional purposes." }, { level: "C2 – Proficient", description: "Near-native fluency with full command of the language." }], whyChooseTitle: "Why Choose Germany?", whyChooseReasons: ["Affordable Tuition Fees.", "Diverse Career Opportunities.", "Fastest Pathways", "Global recognition.", "High-Quality teaching.", "PR in Europe.", "Research facilities."], faqs: [] },
  { title: "French Language Training", slug: "french", fullDescription: ["French is one of the most widely spoken international languages and holds great value for students and professionals planning to study, work, or settle abroad.", "The course follows the CEFR, ensuring structured learning from beginner to advanced levels.", "Our training emphasizes interactive learning through conversations, role plays, and real-life scenarios.", "Whether you are preparing for DELF/DALF exams or enhancing career prospects, our program provides the right foundation.", "Mastering French opens doors to global opportunities across Europe, Canada, and other French-speaking regions."], levels: [{ level: "A1 – Beginner", description: "Learn basic expressions and simple everyday communication." }, { level: "A2 – Elementary", description: "Understand frequently used phrases and routine conversations." }, { level: "B1 – Intermediate", description: "Communicate confidently in daily and workplace situations." }, { level: "B2 – Upper Intermediate", description: "Develop fluency and handle complex discussions." }, { level: "C1 – Advanced", description: "Use French effectively for academic and professional purposes" }], whyChooseTitle: "Why Choose French?", whyChooseReasons: ["Diverse Career Opportunities.", "Experienced & Certified Trainers", "Focus on Real-Life Communication", "Exam Preparation Support", "Career & Study Abroad Oriented", "Flexible Learning Options"], faqs: [] },
  { title: "IELTS Training", slug: "ielts", fullDescription: ["Bright Institutes offers comprehensive IELTS training in Hyderabad, designed for students and professionals aiming to study, work, or settle abroad.", "Our expert trainers focus on all four modules—Listening, Reading, Writing, and Speaking—using proven strategies to help you achieve your target band score.", "We provide personalized coaching, regular mock tests, real exam-pattern practice, and individual feedback.", "At Bright Institutes, we emphasize practical learning, time-management techniques, and exam-oriented preparation.", "Prepare with confidence at Bright Institutes and take the next step toward international education and global career opportunities."], testFormat: [{ section: "Listening (30 minutes)", details: "4 recorded sections • 40 questions total • Tests ability to understand spoken English" }, { section: "Reading (60 minutes)", details: "3 passages • 40 questions • Assesses comprehension and analytical reading skills" }, { section: "Writing (60 minutes)", details: "Academic: Describe visual data, Essay writing • General Training: Letter writing, Essay writing" }, { section: "Speaking (11–14 minutes)", details: "Face-to-face interview • 3 parts: Introduction, Cue Card, Discussion" }], eligibilityIntro: "IELTS is open to anyone wishing to study, work, or migrate abroad. No minimum academic qualifications or age restrictions.", eligibility: [{ title: "Minimum Age", value: "16 Years" }, { title: "No Upper Age Limit", value: "Open to all age groups" }, { title: "Qualifications", value: "No specific qualifications required" }, { title: "Nationality", value: "Candidates from any country" }], faqs: [{ question: "How long is the IELTS score valid?", answer: "IELTS scores are valid for 2 years from the test date." }, { question: "What are the types of IELTS tests?", answer: "There are two main types: IELTS Academic and IELTS General Training" }, { question: "What is the IELTS band score?", answer: "Scores range from 0 to 9 bands, assessing Listening, Reading, Writing, and Speaking skills." }, { question: "Is IELTS difficult?", answer: "Difficulty depends on your English level. Proper preparation significantly improves performance." }, { question: "Is IELTS accepted worldwide?", answer: "Yes, IELTS is accepted by universities, employers, and immigration authorities globally." }] },
  { title: "PTE Language Course", slug: "pte", fullDescription: ["Our PTE Language Course is designed to help students and professionals excel in the Pearson Test of English (PTE Academic).", "The course focuses on all four essential modules — Speaking, Writing, Reading, and Listening — ensuring balanced skill development.", "Our training methodology combines conceptual understanding with exam-oriented preparation.", "With regular assessments, performance tracking, and targeted improvement plans, we ensure consistent progress."], testFormat: [{ section: "Speaking & Writing (Combined)", details: "Personal Introduction • Read Aloud • Repeat Sentence • Describe Image • Essay Writing" }, { section: "Reading Section", details: "Fill in the Blanks • Multiple Choice • Re-order Paragraphs" }, { section: "Listening Section", details: "Summarize Spoken Text • Multiple Choice • Fill in the Blanks • Write from Dictation" }], eligibilityIntro: "PTE is open to anyone wishing to study, work, or migrate abroad. No minimum academic qualifications or age restrictions.", eligibility: [{ title: "Minimum Age", value: "16 Years" }, { title: "No Upper Age Limit", value: "Open to all age groups" }, { title: "Qualifications", value: "No specific qualifications required" }, { title: "Nationality", value: "Candidates from any country" }], faqs: [{ question: "What is PTE Academic?", answer: "PTE Academic is a computer-based English proficiency test accepted by universities and governments worldwide." }, { question: "How long is the PTE score valid?", answer: "PTE scores are valid for 2 years." }, { question: "Is PTE easier than IELTS?", answer: "Difficulty varies by individual. PTE suits candidates comfortable with computer-based testing." }, { question: "How long does the PTE exam take?", answer: "Approximately 2 hours." }, { question: "How quickly can I improve my PTE score?", answer: "With consistent practice, improvement is often seen within 4–8 weeks." }] },
  { title: "Arabic Language Course", slug: "arabic", fullDescription: ["Our Arabic Language Course is designed for students, professionals, and travelers who want to develop strong Arabic communication skills.", "The course focuses on all four essential language skills: speaking, listening, reading, and writing.", "Our training follows a level-based structure suitable for beginners to advanced learners.", "Learning Arabic opens doors to global career opportunities across the Middle East and beyond."], faqs: [{ question: "Who can join the Arabic Language Course?", answer: "Anyone including students, professionals, beginners, and individuals planning to work or travel abroad." }, { question: "Is the course suitable for job seekers?", answer: "Absolutely, Arabic skills enhance opportunities in Gulf and international markets." }, { question: "Why should I learn Arabic?", answer: "Arabic boosts career prospects, cultural understanding, travel, and academic opportunities." }, { question: "Do you provide certification?", answer: "Yes, certification is provided upon successful course completion." }, { question: "Are there different course levels?", answer: "Yes, structured levels from beginner to advanced proficiency." }] },
  { title: "Duolingo Language Course", slug: "duolingo", fullDescription: ["The Duolingo Language Course is designed for students and professionals who want to build strong language skills through engaging, interactive learning methods.", "This course focuses on practical language usage, helping learners gain confidence in real-life communication.", "Learners benefit from flexible study schedules, mobile-friendly access, and vocabulary-building exercises.", "The Duolingo Language Course is ideal for individuals planning to study abroad, migrate, or enhance career opportunities.", "With consistent learning and expert guidance, students can achieve language proficiency efficiently."], faqs: [] },
];

// ─── Air Ticket Booking Data ───
const airTicketCountries = [
  { name: "India", flag: "🇮🇳", code: "IN" },
  { name: "Germany", flag: "🇩🇪", code: "DE" },
  { name: "USA", flag: "🇺🇸", code: "US" },
  { name: "UK", flag: "🇬🇧", code: "GB" },
  { name: "Canada", flag: "🇨🇦", code: "CA" },
  { name: "Australia", flag: "🇦🇺", code: "AU" },
  { name: "UAE", flag: "🇦🇪", code: "AE" },
  { name: "Saudi Arabia", flag: "🇸🇦", code: "SA" },
  { name: "France", flag: "🇫🇷", code: "FR" },
  { name: "Russia", flag: "🇷🇺", code: "RU" },
  { name: "Turkey", flag: "🇹🇷", code: "TR" },
  { name: "Malaysia", flag: "🇲🇾", code: "MY" },
  { name: "Singapore", flag: "🇸🇬", code: "SG" },
  { name: "Japan", flag: "🇯🇵", code: "JP" },
  { name: "South Korea", flag: "🇰🇷", code: "KR" },
  { name: "Italy", flag: "🇮🇹", code: "IT" },
  { name: "Spain", flag: "🇪🇸", code: "ES" },
  { name: "Thailand", flag: "🇹🇭", code: "TH" },
];

const partnerAirlines = [
  { name: "Emirates", code: "EK" },
  { name: "Qatar Airways", code: "QR" },
  { name: "Air India", code: "AI" },
  { name: "IndiGo", code: "6E" },
  { name: "Etihad Airways", code: "EY" },
  { name: "Turkish Airlines", code: "TK" },
  { name: "Lufthansa", code: "LH" },
  { name: "British Airways", code: "BA" },
  { name: "Singapore Airlines", code: "SQ" },
  { name: "Malaysia Airlines", code: "MH" },
  { name: "Saudia", code: "SV" },
  { name: "FlyDubai", code: "FZ" },
  { name: "Air Arabia", code: "G9" },
  { name: "Vistara", code: "UK" },
  { name: "SpiceJet", code: "SG" },
  { name: "Oman Air", code: "WY" },
];

// ─── Visa Categories (Visa Services page) ───
const visaCategories = [
  { title: "Student Visa", description: "Complete guidance for student visa applications to Germany, Australia, USA, UK, Canada, and Europe. From document preparation to interview coaching, we ensure a smooth visa process.", features: ["University admission support", "Document verification", "Financial proof guidance", "Interview preparation", "Post-visa travel planning"] },
  { title: "Work Visa / Employment Visa", description: "Comprehensive work visa support for professionals seeking career opportunities abroad.", features: ["Job offer verification", "Work permit processing", "Employer coordination", "Residence permit guidance", "Family reunification support"] },
  { title: "Visit / Tourist Visa", description: "Expert assistance for tourist and visit visas. Whether visiting family, attending conferences, or traveling for leisure.", features: ["Invitation letter guidance", "Travel insurance", "Itinerary planning", "Financial documentation", "Embassy appointment booking"], destinations: { global: ["Canada", "UK", "Europe", "Australia", "Vietnam", "Thailand", "Singapore", "Malaysia", "New Zealand", "Sri Lanka", "South Korea", "Brazil", "Russia", "China", "Japan", "Indonesia"], gulf: ["Dubai", "Bahrain", "Qatar", "Oman", "Saudi Arabia"] } },
  { title: "Business Visa", description: "Professional business visa services for entrepreneurs and corporate professionals.", features: ["Business invitation letters", "Company registration documents", "Trade fair participation", "Meeting scheduling support", "Multi-entry visa guidance"] },
  { title: "Family Visa", description: "Reunite with your loved ones abroad with our family visa services.", features: ["Spouse visa applications", "Dependent visa processing", "Family reunion documentation", "Integration course guidance", "Settlement support"] },
];
